{% set version = "1.1.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-semplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/semPlot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/semPlot/semPlot_{{ version }}.tar.gz
  sha256: 56921be740f967884ff3af69377fd17e8bfef1bfe582c86399e64c5dabab4ca2

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-openmx
    - r-xml
    - r-colorspace
    - r-corpcor
    - r-igraph >=0.6_3
    - r-lavaan >=0.5_11
    - r-lisreltor
    - r-plyr
    - r-qgraph >=1.2.4
    - r-regsem
    - r-rockchalk
    - r-sem >=3.1_0

  run:
    - r-base
    - r-openmx
    - r-xml
    - r-colorspace
    - r-corpcor
    - r-igraph >=0.6_3
    - r-lavaan >=0.5_11
    - r-lisreltor
    - r-plyr
    - r-qgraph >=1.2.4
    - r-regsem
    - r-rockchalk
    - r-sem >=3.1_0

test:
  commands:
    - $R -e "library('semPlot')"           # [not win]
    - "\"%R%\" -e \"library('semPlot')\""  # [win]

about:
  home: https://github.com/SachaEpskamp/semPlot

  license: GPL-2.0-only
  summary: Path diagrams and visual analysis of various SEM packages' output.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
